Repository Dominicod/little-esty-shop, pull requests merged in 2022-09, with the labels that each got.

#1 Feat/database schema
  .gitignore
  .idea/.gitignore
  .idea/csv-plugin.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/little-esty-shop.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  app/assets/javascripts/customers.coffee
  app/assets/javascripts/invoice_items.coffee
  app/assets/javascripts/invoices.coffee
  app/assets/javascripts/items.coffee
  app/assets/javascripts/merchants.coffee
  app/assets/javascripts/transactions.coffee
  app/assets/stylesheets/customers.scss
  app/assets/stylesheets/invoice_items.scss
  app/assets/stylesheets/invoices.scss
  app/assets/stylesheets/items.scss
  app/assets/stylesheets/merchants.scss
  app/assets/stylesheets/transactions.scss
  app/controllers/customers_controller.rb
  app/controllers/invoice_items_controller.rb
  app/controllers/invoices_controller.rb
  app/controllers/items_controller.rb
  app/controllers/merchants_controller.rb
  app/controllers/transactions_controller.rb
  app/helpers/customers_helper.rb
  app/helpers/invoice_items_helper.rb
  app/helpers/invoices_helper.rb
  app/helpers/items_helper.rb
  app/helpers/merchants_helper.rb
  app/helpers/transactions_helper.rb
  app/models/customer.rb
  app/models/invoice.rb
  app/models/invoice_item.rb
  app/models/item.rb
  app/models/merchant.rb
  app/models/transaction.rb
  config/routes.rb
  db/migrate/1_create_customers.rb
  db/migrate/2_create_invoices.rb
  db/migrate/3_create_merchants.rb
  db/migrate/4_create_items.rb
  db/migrate/5_create_transactions.rb
  db/migrate/6_create_invoice_items.rb
  db/schema.rb
  lib/tasks/.keep
  lib/tasks/csv_load.rake
  spec/models/customer_spec.rb
  spec/models/invoice_item_spec.rb
  spec/models/invoice_spec.rb
  spec/models/item_spec.rb
  spec/models/merchant_spec.rb
  spec/models/transaction_spec.rb
Labels: enhancement

#43 Feat: Create admin dashboard index and links
  app/controllers/admin_controller.rb
  app/models/admin.rb
  app/views/admin/index.html.erb
  config/routes.rb
  spec/features/admin/index_spec.rb
Labels: enhancement

#46 feat: create rake task to load csv data into test db
  db/mock/customers.csv
  db/mock/invoice_items.csv
  db/mock/invoices.csv
  db/mock/items.csv
  db/mock/merchants.csv
  db/mock/transactions.csv
  lib/tasks/csv_load_mock.rake
  lib/tasks/test_db.rake
Labels: enhancement

#47 Feat: created user story 3 for admin and fixed mocked data and delete…
  app/controllers/admin_controller.rb
  app/models/admin.rb
  app/models/customer.rb
  app/views/admin/index.html.erb
  db/mock/items.csv
  spec/features/admin/index_spec.rb
  spec/features/merchants/dashboard_spec.rb
  spec/models/customer_spec.rb
Labels: enhancement

#48 Feat/user story 4 admin
  app/controllers/admin_controller.rb
  app/models/customer.rb
  app/models/invoice.rb
  app/views/admin/index.html.erb
  db/mock/invoice_items.csv
  spec/features/admin/index_spec.rb
  spec/models/invoice_spec.rb
Labels: enhancement

#49 Feat: Added logic to format the dates of invoices, and tests associated
  app/models/invoice.rb
  app/views/admin/index.html.erb
  spec/features/admin/index_spec.rb
  spec/models/invoice_spec.rb
Labels: enhancement

#51 Fix/admin view naming
  app/controllers/admin_controller.rb
  app/models/customer.rb
  app/views/admin/index.html.erb
  db/mock/customers.csv
  db/mock/invoices.csv
  db/mock/merchants.csv
  db/mock/transactions.csv
  spec/features/admin/index_spec.rb
  spec/models/customer_spec.rb
Labels: bug

#52 Completes spec and feature for merchant items index page
  app/controllers/items_controller.rb
  app/views/items/index.html.erb
  db/mock/customers.csv
  db/mock/invoices.csv
  db/mock/merchants.csv
  db/mock/transactions.csv
  spec/features/merchants/items/index_spec.rb
Labels: enhancement

#55 Test: created and updated tests so that they are testing properly
  app/views/admin/index.html.erb
  spec/features/admin/index_spec.rb
Labels: bug

#64 10 merchant items edit page
  app/controllers/items_controller.rb
  app/views/items/edit.html.erb
  app/views/items/show.html.erb
  app/views/layouts/application.html.erb
  config/routes.rb
  spec/features/merchants/items/edit_spec.rb
  spec/features/merchants/items/show_spec.rb
Labels: enhancement

#68 Feat/admin invoices show v3
  app/controllers/admin/invoices_controller.rb
  app/models/invoice.rb
  app/views/admin/invoices/show.html.erb
  config/routes.rb
  spec/features/admin/invoices/show_spec.rb
  spec/models/invoice_spec.rb
Labels: enhancement

#71 Feat/admin merchant buttomns
  app/controllers/admin/merchants_controller.rb
  app/controllers/items_controller.rb
  app/models/merchant.rb
  app/views/admin/merchants/index.html.erb
  app/views/items/index.html.erb
  db/migrate/3_create_merchants.rb
  db/schema.rb
  spec/features/admin/merchants/index_spec.rb
  spec/features/merchants/items/index_spec.rb
  spec/models/merchant_spec.rb
Labels: enhancement

#73 13 merchant item create
  app/controllers/items_controller.rb
  app/views/items/index.html.erb
  app/views/items/new.html.erb
  config/routes.rb
  spec/features/merchants/items/new_spec.rb
Labels: enhancement

#72 Feat/admin invoices show v3
  app/controllers/admin/invoices_controller.rb
  app/views/admin/invoices/index.html.erb
  app/views/admin/invoices/show.html.erb
  config/routes.rb
  spec/features/admin/invoices/show_spec.rb
Labels: enhancement

#77 Feat/admin merchant create v2
  app/controllers/admin/merchants_controller.rb
  app/views/admin/merchants/index.html.erb
  app/views/admin/merchants/new.html.erb
  config/routes.rb
  db/migrate/1_create_customers.rb
  db/migrate/3_create_merchants.rb
  db/migrate/4_create_items.rb
  db/migrate/5_create_transactions.rb
  db/migrate/6_create_invoice_items.rb
  db/schema.rb
  lib/tasks/csv_load.rake
  lib/tasks/csv_load_mock.rake
  spec/features/admin/merchants/edit_spec.rb
  spec/features/admin/merchants/index_spec.rb
  spec/features/admin/merchants/new_spec.rb
  spec/features/admin/merchants/show_spec.rb
Labels: bug, enhancement

#81 Feat/admin invoice show v4
  app/controllers/admin/invoices_controller.rb
  app/views/admin/invoices/index.html.erb
  config/routes.rb
  spec/features/admin/invoices/index_spec.rb
  spec/features/admin/invoices/show_spec.rb
Labels: enhancement

#83 16/17 merchant invoice index/show
  Gemfile.lock
  app/controllers/merchant/invoices_controller.rb
  app/models/merchant.rb
  app/views/merchant/invoices/index.html.erb
  app/views/merchant/invoices/show.html.erb
  config/routes.rb
  spec/features/merchant/invoices/index_spec.rb
  spec/features/merchant/invoices/show_spec.rb
Labels: enhancement

#84 Feat/top 5 merchant by revenue
  Gemfile.lock
  app/controllers/admin/merchants_controller.rb
  app/models/customer.rb
  app/models/merchant.rb
  app/views/admin/merchants/index.html.erb
  spec/features/admin/merchants/edit_spec.rb
  spec/features/admin/merchants/index_spec.rb
  spec/features/admin/merchants/show_spec.rb
  spec/models/merchant_spec.rb
Labels: bug, enhancement

#87 Feat/merchant best day
  app/controllers/customers_controller.rb
  app/controllers/invoice_items_controller.rb
  app/controllers/items_controller.rb
  app/controllers/merchant/dashboard_controller.rb
  app/controllers/merchants_controller.rb
  app/controllers/transactions_controller.rb
  app/models/merchant.rb
  app/views/admin/merchants/index.html.erb
  app/views/items/index.html.erb
  app/views/items/show.html.erb
  app/views/merchant/dashboard/index.html.erb
  config/routes.rb
  spec/features/admin/merchants/index_spec.rb
  spec/features/merchant/dashboard_spec.rb
  spec/models/merchant_spec.rb
Labels: enhancement

#85 Fix: the PK reset function, due to a misspell
  lib/tasks/csv_load.rake
  lib/tasks/csv_load_mock.rake
Labels: bug

#88 Feat: introduce invoice link to each incomplete invoice
  app/views/admin/index.html.erb
Labels: enhancement

#89 18 merchant invoice show item info
  app/controllers/merchant/invoices_controller.rb
  app/models/invoice_item.rb
  app/views/merchant/invoices/show.html.erb
  spec/features/merchant/invoices/show_spec.rb
  spec/models/invoice_item_spec.rb
Labels: enhancement

#91 Fix: add enhanced testing to merchant invoices
  spec/features/merchant/invoices/show_spec.rb
Labels: bug

#95 Create return in service to mock API calls
  .gitignore
  app/controllers/application_controller.rb
  app/services/github_service.rb
  config/application.yml
  spec/features/admin/dashboard/index_spec.rb
Labels: enhancement

#99 Feat: introduce webmock to test and validate API calls
  Gemfile
  Gemfile.lock
  app/services/github_service.rb
  spec/features/admin/dashboard/index_spec.rb
  spec/features/admin/invoices/index_spec.rb
  spec/features/admin/invoices/show_spec.rb
  spec/features/admin/merchants/edit_spec.rb
  spec/features/admin/merchants/index_spec.rb
  spec/features/admin/merchants/new_spec.rb
  spec/features/admin/merchants/show_spec.rb
  spec/features/merchant/dashboard_spec.rb
  spec/features/merchant/invoices/index_spec.rb
  spec/features/merchant/invoices/show_spec.rb
  spec/features/merchant/items/edit_spec.rb
  spec/features/merchant/items/index_spec.rb
  spec/features/merchant/items/new_spec.rb
  spec/features/merchant/items/show_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: enhancement

#102 Feat: add tests and logic to github API story 3
  Gemfile
  app/controllers/application_controller.rb
  app/facades/github_facade.rb
  app/poros/github_pulls.rb
  app/services/github_service.rb
  app/views/layouts/application.html.erb
  config/application.yml
  spec/features/admin/dashboard/index_spec.rb
  spec/features/admin/invoices/index_spec.rb
  spec/features/admin/invoices/show_spec.rb
  spec/features/admin/merchants/edit_spec.rb
  spec/features/admin/merchants/index_spec.rb
  spec/features/admin/merchants/new_spec.rb
  spec/features/admin/merchants/show_spec.rb
  spec/features/merchant/dashboard_spec.rb
  spec/features/merchant/invoices/index_spec.rb
  spec/features/merchant/invoices/show_spec.rb
  spec/features/merchant/items/edit_spec.rb
  spec/features/merchant/items/index_spec.rb
  spec/features/merchant/items/new_spec.rb
  spec/features/merchant/items/show_spec.rb
  spec/rails_helper.rb
Labels: enhancement

#115 Feat/merchant bulk discounts index
  app/controllers/merchant/bulk_discounts_controller.rb
  app/services/github_service.rb
  app/views/merchant/bulk_discounts/index.html.erb
  app/views/merchant/bulk_discounts/show.html.erb
  app/views/merchant/dashboard/index.html.erb
  config/routes.rb
  db/schema.rb
  db/seeds.rb
  lib/tasks/csv_load.rake
  lib/tasks/csv_load_mock.rake
  spec/features/merchant/bulk_discounts/index_spec.rb
  spec/features/merchant/bulk_discounts/show_spec.rb
  spec/features/merchant/dashboard_spec.rb
Labels: enhancement

#116 Feat/merchant bulk discount create
  app/controllers/merchant/bulk_discounts_controller.rb
  app/views/merchant/bulk_discounts/index.html.erb
  app/views/merchant/bulk_discounts/new.html.erb
  config/routes.rb
  spec/features/merchant/bulk_discounts/index_spec.rb
  spec/features/merchant/bulk_discounts/new_spec.rb
  spec/features/merchant/bulk_discounts/show_spec.rb
Labels: enhancement

#117 Feat/merchant bulk discount delete
  app/controllers/merchant/bulk_discounts_controller.rb
  app/views/merchant/bulk_discounts/index.html.erb
  db/seeds.rb
  spec/features/merchant/bulk_discounts/index_spec.rb
Labels: enhancement

#118 Fix: create a class variable in order to increase page load time
  app/controllers/application_controller.rb
Labels: bug

#119 Feat/merchant bulk discount edit
  app/controllers/merchant/bulk_discounts_controller.rb
  app/controllers/merchant/invoices_controller.rb
  app/views/merchant/bulk_discounts/edit.html.erb
  app/views/merchant/bulk_discounts/new.html.erb
  app/views/merchant/bulk_discounts/show.html.erb
  app/views/merchant/invoices/show.html.erb
  db/migrate/20220922210539_create_bulk_discounts.rb
  db/schema.rb
  lib/tasks/csv_load.rake
  lib/tasks/csv_load_mock.rake
  spec/features/merchant/bulk_discounts/edit_spec.rb
  spec/features/merchant/bulk_discounts/show_spec.rb
Labels: bug, enhancement

#120 Feat: Merchant index logic created and tests created
  app/controllers/application_controller.rb
  app/controllers/merchants_controller.rb
  app/views/application/index.html.erb
  app/views/application/welcome.html.erb
  app/views/merchants/index.html.erb
  config/routes.rb
  doc/db_setup.md
  lib/tasks/csv_load.rake
  lib/tasks/csv_load_mock.rake
  spec/features/admin/dashboard/index_spec.rb
  spec/features/admin/invoices/index_spec.rb
  spec/features/admin/invoices/show_spec.rb
  spec/features/admin/merchants/index_spec.rb
  spec/features/admin/merchants/new_spec.rb
  spec/features/merchant/dashboard_spec.rb
  spec/features/merchant/index_spec.rb
  spec/features/merchant/items/index_spec.rb
  spec/features/merchant/items/new_spec.rb
  spec/features/merchant/items/show_spec.rb
  spec/models/invoice_item_spec.rb
  spec/models/item_spec.rb
  spec/models/merchant_spec.rb
Labels: enhancement

#121 Feat/create merchant index
  app/controllers/merchants_controller.rb
  app/views/admin/merchants/show.html.erb
  app/views/application/welcome.html.erb
  app/views/merchants/index.html.erb
  spec/features/admin/merchants/show_spec.rb
  spec/features/merchant/index_spec.rb
Labels: enhancement

#122 Feat/merchant bulk discounts invoice
  app/controllers/merchant/invoices_controller.rb
  app/models/application_record.rb
  app/models/invoice_item.rb
  app/views/merchant/invoices/show.html.erb
  spec/features/merchant/bulk_discounts/edit_spec.rb
  spec/features/merchant/bulk_discounts/new_spec.rb
  spec/features/merchant/invoices/show_spec.rb
Labels: enhancement

#123 Feat: update AR query in discountable to be more efficent
  app/controllers/merchant/invoices_controller.rb
  app/models/invoice_item.rb
Labels: enhancement

#124 Feat/merchant bulk discounts invoice
  app/controllers/merchant/invoices_controller.rb
  app/models/bulk_discount.rb
  app/models/invoice_item.rb
  app/views/merchant/invoices/show.html.erb
  spec/features/merchant/invoices/show_spec.rb
  spec/models/bulk_discount_spec.rb
  spec/models/invoice_item_spec.rb
Labels: enhancement

#125 Test: create tests for refactor of model methods. Feat: create PORO t…
  app/controllers/merchant/invoices_controller.rb
  app/models/invoice.rb
  app/models/invoice_item.rb
  app/objects/invoice_item_discounted.rb
  app/views/merchant/invoices/show.html.erb
  db/seeds.rb
  spec/models/invoice_item_spec.rb
  spec/models/invoice_spec.rb
Labels: enhancement

#126 Test: Add more tests to invoice show_spec
  app/views/merchant/invoices/show.html.erb
  spec/features/merchant/invoices/show_spec.rb
Labels: enhancement

#127 Feat/refactor to db logic
  app/controllers/merchant/bulk_discounts_controller.rb
  app/controllers/merchant/invoices_controller.rb
  app/models/bulk_discount.rb
  app/models/invoice.rb
  app/models/invoice_item.rb
  app/objects/invoice_item_discounted.rb
  app/views/merchant/invoices/show.html.erb
  db/migrate/6_create_bulk_discounts.rb
  db/migrate/7_create_invoice_items.rb
  db/migrate/8_add_status_to_items.rb
  db/schema.rb
  db/seeds.rb
  spec/features/merchant/invoices/show_spec.rb
  spec/models/bulk_discount_spec.rb
  spec/models/invoice_item_spec.rb
  spec/models/invoice_spec.rb
Labels: enhancement

#128 Feat/show discounted revenue
  app/controllers/merchant/bulk_discounts_controller.rb
  app/controllers/merchant/invoices_controller.rb
  app/models/invoice.rb
  app/models/invoice_item.rb
  app/views/admin/invoices/show.html.erb
  app/views/merchant/invoices/show.html.erb
  spec/features/admin/invoices/show_spec.rb
  spec/features/merchant/bulk_discounts/edit_spec.rb
  spec/features/merchant/invoices/show_spec.rb
  spec/models/invoice_spec.rb
  spec/models/merchant_spec.rb
Labels: enhancement

#129 Refactor: fixed a few methods requiring ruby logic and converted them…
  app/controllers/admin/invoices_controller.rb
  app/models/invoice.rb
  app/models/invoice_item.rb
  spec/features/admin/invoices/show_spec.rb
  spec/models/invoice_spec.rb
Labels: enhancement

#130 Feat/api introduction
  app/controllers/merchant/bulk_discounts_controller.rb
  app/facades/date_facade.rb
  app/models/invoice_item.rb
  app/objects/date_holiday.rb
  app/services/date_service.rb
  app/views/merchant/bulk_discounts/index.html.erb
  spec/features/merchant/bulk_discounts/index_spec.rb
  spec/rails_helper.rb
Labels: enhancement
